#!/usr/bin/env python3
from pathlib import Path
import datetime
import tomllib

ROOT = Path(__file__).resolve().parents[1]
m = tomllib.loads((ROOT / "release.toml").read_text(encoding="utf-8"))

body = f"""# Evidence Report — Neural Boundary Game {m['display_version']}

Generated: {datetime.datetime.utcnow().replace(microsecond=0).isoformat()}Z

## Release identity

- Product: {m['product']}
- Version: {m['display_version']}
- ABI version: {m['abi_version']}
- Product version packed: {m['product_version_packed']}
- Replay schema: `{m['replay_schema']}`
- Hash algorithm: `{m['state_hash_algorithm']}`
- RNG algorithm: `{m['rng_algorithm']}`
- Tick rate: {m['tick_rate_hz']} Hz

## Evidence gates

- Rust workspace checks
- WASM build
- Replay validation
- Version consistency
- Hygiene
- Internal links
- ABI/WASM presence
- PWA cache surface
- Source manifest generation

## Release note

This report is generated by `tools/build_evidence_report.py`.
"""

(ROOT / "EVIDENCE_REPORT.md").write_text(body, encoding="utf-8")
print("Wrote EVIDENCE_REPORT.md")
